# Generated by Django 2.1.5 on 2019-12-26 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191226_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, max_length=70, unique=True),
        ),
    ]
